stages:
  - pre-build
  - build
  #- test
  - release
  - release-tag
  #- deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/aem:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/aem:latest
  CONTAINER_RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE/aem:$CI_COMMIT_TAG
  JENKINS_USER: admin
  JENKINS_USER_PASSWORD: admin


get aem jar:
  stage: pre-build
  image: aemdesign/centos-java-buildpack:latest
  cache:
    key: aemdesign-aem
    paths:
      - aemdesign-aem/dist
    policy: push
  script:
    - git lfs install
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/aem.design/aemdesign-aem.git


build docker image:
  stage: build
  image:
    name: docker:stable
  services:
    - docker:dind
  cache:
    key: aemdesign-aem
    paths:
      - aemdesign-aem/dist
    policy: pull

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build --pull -t "$CONTAINER_TEST_IMAGE" .
    - docker push "$CONTAINER_TEST_IMAGE"

release image master:
  stage: release
  image: docker:stable
  services:
    - docker:dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE"
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master

release image tag:
  stage: release-tag
  image: docker:stable
  services:
    - docker:dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE_TAG"
    - docker push "$CONTAINER_RELEASE_IMAGE_TAG"
  only:
    - tags
